default_platform(:mac)

before_all do

  setup_ci(force: "true")

end

platform :mac do

  lane :build_develop do
    build_app(scheme: "Development")
  end

  lane :build_release do
    build_app(scheme: "Release")
  end

end
