name: CI

# For testing this action, run the workflow when someone (yours truly) stars the repo
on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - name: Print
      run: echo "detected a push" 
    - uses: actions/checkout@v1
    - name: Build
      run: fastlane build
    - uses: actions/upload-artifact@master
    - name: Upload OSRS Touch Bar.app
      uses: actions/upload-artifact@v1
      with:
        name: OSRS Touch Bar
        path: OSRS Touch Bar.app
