name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Build
    - uses: actions/checkout@v1
      run: fastlane build

    - name: Compress Build Artifacts
      run: zip -r osrs-touch-bar.zip "OSRS Touch Bar.app"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: osrs-touch-bar.zip
        path: osrs-touch-bar.zip
