name: CI

on: 
  push:
    branches:
      - master


jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build OSRS Touch Bar (Release) 
      run: fastlane build_release

    - name: Compress Build Artifacts
      run: zip -r osrs-touch-bar.zip "OSRS Touch Bar.app"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: osrs-touch-bar.zip
        path: osrs-touch-bar.zip
